Use project;

select * from cust_shopping;

-- rest of the column names I changed from the dataset toolbar on the left by clicking on it and selecting alter table option.

select * from cust_shopping ;


-- Q1. What is the total revenue generated by male vs. female customers?

select Gender, SUM(Purchase_Amount) as Revenue from cust_shopping
group by Gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select Customer_ID, Purchase_Amount from cust_shopping
where Discount_Applied ='Yes' and 
Purchase_Amount > (select Avg(purchase_amount) from cust_shopping);

-- Q3. Which are the top 5 products with the highest average review rating?

select * from cust_shopping ;

select item_purchased, Round(avg(review_rating), 2) from cust_shopping
group by item_purchased 
order by item_purchased, avg(review_rating) DESC limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type , avg(purchase_amount) as avg_shipping_amount from cust_shopping
where shipping_type in ('Express', 'Standard')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue

select subscription_status, Sum(Purchase_amount), avg(Purchase_amount) from cust_shopping
group by subscription_status;

-- Q6. which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
100 * Sum(case when discount_applied ='yes' then 1 else 0 end)/count(*) as percent_purchase 
from cust_shopping
group by item_purchased 
order by percent_purchase DESC limit 5; 

-- Q7. Segment customers into New, Returning, and Loyal 
--     based on their total number of previous purchases, and show the count of each segment.

with segment_count as(
select case when previous_purchases <= 5 then 'New'
            when previous_purchases <= 15 then 'Returning'
            else 'Loyal'
	   End as segments
 From cust_shopping)
 select segments,count(segments) from segment_count
 group by segments;

-- Q8. What are the top 3 most purchased products within each category?

with top_purchased as(
select category , item_purchased, count(customer_id) as items_counts,
	Row_Number() over( partition by category order by count(customer_id) DESC) as items_ranks from cust_shopping
group by category, item_purchased 
)
select items_ranks, category, item_purchased, items_counts 
from top_purchased 
where items_ranks <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)
--     also likely to subscribe?
  
  select 
  100 * count(case when previous_purchases > 5 and subscription_status ='yes' then 1 end) 
		  /count(case when previous_purchases > 5 then 1 end) as Yes_percent_count,
  100 * count(case when previous_purchases <= 5 and subscription_status ='yes' then 1 end) 
		   /count(case when previous_purchases <=5 then 1 end) as No_percent_count2
  from cust_shopping;
  
  -- OR we can do this
  
select subscription_status,
count(customer_id) as repeat_buyers
from cust_shopping
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
  
 select 
        CASE
             when age <= 20 then 'teenagers'
             when age <= 35 then 'young_adults' 
             when age <= 60 then 'adults' 
             else 'senior citizens'
		END as age_group , 
	SUM(purchase_amount) as revenue_amount
 from cust_shopping 
 group by age_group
 order by  revenue_amount Desc;
         
  
  
  
